### ISSUE TITLE
Problema al dibujar calendario

### ISSUE THREAD

**Issue by felipinbombin** [SmartcitySantiagoChile/fondefVizServer#5]
Encontré el siguiente 🐛 

Rama: https://github.com/SmartcitySantiagoChile/fondefVizServer/tree/feature/newCalendar

Para reproducir:
- Abro el calendario y selecciono los días entre 07-10-2019 al 24-10-2019
- Presiono el botón "guardar"
- Abro el calendario nuevamente
- Presiono el botón "eliminar selección"
- Con la opción "Añadir rango" activada selecciono un día, por ejemplo el 01-04-2019
- Muevo el mouse al siguiente día (02-04-2019)
- BUG: Los días seleccionados en el primer punto aparecen activos cuando no deberían. Además, no se vuelven a ocultar con el botón "eliminar selección"

**Comment by Bastianleaf** [comment]
Encontré el problema, el calendario maneja dos arreglos, uno que es simil a lo que se almacena en localStorage, cuando uno guarda los datos y otro que es temporal para cuando uno hace selección o borrado en el calendario. El bug sucedía porque al gatillar eventos del mouse como `globalout` o `over`, se repintaban los cuadros de ambos arreglos, el de localStorage junto con el temporal. La solución es que se repinten solo los temporales.

Ya hice commit y push de la versión corregida.
